-- MockMind SQLite Schema
-- Run: sqlite3 mockmind.db < schema.sql

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(80) UNIQUE NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    is_admin BOOLEAN DEFAULT 0,
    xp INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subject (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) UNIQUE NOT NULL,
    icon VARCHAR(10) DEFAULT '📚'
);

CREATE TABLE IF NOT EXISTS question (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    grade INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    question_type VARCHAR(20) NOT NULL,  -- very_short, short, long
    question_text TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    marks INTEGER DEFAULT 1,
    FOREIGN KEY (subject_id) REFERENCES subject(id)
);

CREATE TABLE IF NOT EXISTS exam (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    grade INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME,
    score REAL DEFAULT 0,
    total_marks INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT 0,
    xp_earned INTEGER DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (subject_id) REFERENCES subject(id)
);

CREATE TABLE IF NOT EXISTS exam_answer (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id INTEGER NOT NULL,
    question_id INTEGER NOT NULL,
    student_answer TEXT DEFAULT '',
    ai_score REAL,
    ai_feedback TEXT,
    FOREIGN KEY (exam_id) REFERENCES exam(id),
    FOREIGN KEY (question_id) REFERENCES question(id)
);

-- Seed Subjects
INSERT INTO subject (name, icon) VALUES
    ('Mathematics', '🔢'),
    ('Science', '🔬'),
    ('English', '📖'),
    ('Hindi', '🇮🇳'),
    ('Social Science', '🌍'),
    ('Computer Science', '💻');

-- Default Admin User (password: admin123)
-- Note: This hash is generated by Werkzeug. For production, create admin via the app.
-- The app auto-creates this admin on first run, so this INSERT is optional.
