"""Seed questions for all grades (1-10) and all subjects."""
from app import app
from extensions import db
from models import Question, Subject


QUESTIONS = {
    'Mathematics': {
        1: [
            ('very_short', 'What is 2 + 3?', '5', 1),
            ('very_short', 'What is 10 - 4?', '6', 1),
            ('very_short', 'What is 3 × 2?', '6', 1),
            ('short', 'If you have 5 apples and give away 2, how many do you have left?', '3 apples', 2),
            ('short', 'Count from 1 to 10 and write all the even numbers.', '2, 4, 6, 8, 10', 2),
            ('short', 'What comes after 15?', '16', 2),
            ('long', 'Draw and explain what a circle, square, and triangle look like. How are they different?', 'A circle is round with no corners. A square has 4 equal sides and 4 corners. A triangle has 3 sides and 3 corners.', 3),
            ('very_short', 'What is 7 + 1?', '8', 1),
            ('very_short', 'How many sides does a triangle have?', '3', 1),
            ('short', 'Write the number that is 1 more than 19.', '20', 2),
        ],
        2: [
            ('very_short', 'What is 15 + 8?', '23', 1),
            ('very_short', 'What is 20 - 7?', '13', 1),
            ('very_short', 'What is 4 × 5?', '20', 1),
            ('short', 'If a dozen means 12, how many eggs are in 2 dozen?', '24 eggs', 2),
            ('short', 'What is the place value of 3 in the number 35?', 'The place value of 3 is 30 (tens place)', 2),
            ('short', 'Write all odd numbers between 10 and 20.', '11, 13, 15, 17, 19', 2),
            ('long', 'Raj has 18 marbles. He gives 5 to Sam and 3 to Rita. How many marbles does Raj have now? Show your work.', 'Raj starts with 18 marbles. He gives away 5 + 3 = 8 marbles. 18 - 8 = 10 marbles remaining.', 3),
            ('very_short', 'What is 9 × 2?', '18', 1),
            ('very_short', 'What is half of 16?', '8', 1),
            ('short', 'Name the shape with 4 equal sides and 4 right angles.', 'Square', 2),
        ],
        3: [
            ('very_short', 'What is 45 + 27?', '72', 1),
            ('very_short', 'What is 8 × 7?', '56', 1),
            ('very_short', 'What is 100 ÷ 5?', '20', 1),
            ('short', 'What is the perimeter of a rectangle with length 8 cm and width 5 cm?', 'Perimeter = 2 × (8 + 5) = 2 × 13 = 26 cm', 2),
            ('short', 'Convert 3 hours into minutes.', '3 × 60 = 180 minutes', 2),
            ('short', 'Round 67 to the nearest ten.', '70', 2),
            ('long', 'A shop sells pencils for ₹5 each and erasers for ₹3 each. Meena buys 4 pencils and 6 erasers. How much does she pay in total?', '4 pencils = 4 × 5 = ₹20. 6 erasers = 6 × 3 = ₹18. Total = 20 + 18 = ₹38.', 3),
            ('very_short', 'What is 63 ÷ 9?', '7', 1),
            ('very_short', 'How many minutes are in 1 hour?', '60', 1),
            ('short', 'Write the fraction for: three-fourths.', '3/4', 2),
        ],
        4: [
            ('very_short', 'What is 256 + 189?', '445', 1),
            ('very_short', 'What is 12 × 12?', '144', 1),
            ('very_short', 'What is the LCM of 4 and 6?', '12', 1),
            ('short', 'Find the area of a rectangle with length 12 cm and breadth 7 cm.', 'Area = length × breadth = 12 × 7 = 84 sq cm', 2),
            ('short', 'Convert 2.5 km to meters.', '2.5 × 1000 = 2500 meters', 2),
            ('short', 'What is 3/4 + 1/4?', '3/4 + 1/4 = 4/4 = 1', 2),
            ('long', 'A train travels at 60 km/h. How far will it travel in 3 hours and 30 minutes? Explain your calculation.', 'Speed = 60 km/h. Time = 3.5 hours. Distance = Speed × Time = 60 × 3.5 = 210 km.', 3),
            ('very_short', 'What is the HCF of 12 and 18?', '6', 1),
            ('very_short', 'How many millimeters in 1 centimeter?', '10', 1),
            ('short', 'Is 37 a prime number? Why?', 'Yes, 37 is a prime number because it has only two factors: 1 and 37.', 2),
        ],
        5: [
            ('very_short', 'What is 15% of 200?', '30', 1),
            ('very_short', 'What is the square of 13?', '169', 1),
            ('very_short', 'Convert 0.75 to a fraction.', '3/4', 1),
            ('short', 'Find the average of 12, 18, 24, and 30.', 'Average = (12+18+24+30)/4 = 84/4 = 21', 2),
            ('short', 'What is the volume of a cube with side 5 cm?', 'Volume = side³ = 5³ = 125 cubic cm', 2),
            ('short', 'Simplify: 2/3 + 5/6', '2/3 + 5/6 = 4/6 + 5/6 = 9/6 = 3/2 = 1.5', 2),
            ('long', 'A rectangular garden is 20m long and 15m wide. A path 2m wide runs around the inside of the garden. Find the area of the path.', 'Outer area = 20 × 15 = 300 sq m. Inner dimensions = (20-4) × (15-4) = 16 × 11 = 176 sq m. Path area = 300 - 176 = 124 sq m.', 3),
            ('very_short', 'What is 3/5 as a decimal?', '0.6', 1),
            ('very_short', 'How many degrees in a right angle?', '90', 1),
            ('short', 'Find the perimeter of an equilateral triangle with side 9 cm.', 'Perimeter = 3 × 9 = 27 cm', 2),
        ],
        6: [
            ('very_short', 'What is -5 + 8?', '3', 1),
            ('very_short', 'What is the value of x in: x + 7 = 15?', '8', 1),
            ('very_short', 'Find the ratio 12:18 in simplest form.', '2:3', 1),
            ('short', 'Find the area of a triangle with base 10 cm and height 6 cm.', 'Area = 1/2 × base × height = 1/2 × 10 × 6 = 30 sq cm', 2),
            ('short', 'Express 3/8 as a percentage.', '3/8 × 100 = 37.5%', 2),
            ('short', 'What are the first 5 multiples of 7?', '7, 14, 21, 28, 35', 2),
            ('long', 'A shopkeeper buys an article for ₹400 and sells it for ₹500. Calculate the profit and profit percentage.', 'Profit = 500 - 400 = ₹100. Profit % = (100/400) × 100 = 25%.', 3),
            ('very_short', 'What is (-3) × (-4)?', '12', 1),
            ('very_short', 'How many lines of symmetry does a square have?', '4', 1),
            ('short', 'Write the algebraic expression: twice a number added to 5.', '2x + 5', 2),
        ],
        7: [
            ('very_short', 'What is (-8) × 5?', '-40', 1),
            ('very_short', 'Solve: 3x = 21', '7', 1),
            ('very_short', 'What is the square root of 64?', '8', 1),
            ('short', 'Find the simple interest on ₹5000 at 10% per annum for 2 years.', 'SI = P×R×T/100 = 5000×10×2/100 = ₹1000', 2),
            ('short', 'If two angles of a triangle are 45° and 65°, find the third angle.', 'Third angle = 180° - 45° - 65° = 70°', 2),
            ('short', 'Express 0.125 as a fraction in simplest form.', '0.125 = 125/1000 = 1/8', 2),
            ('long', 'The marks obtained by 10 students in a test are: 45, 67, 82, 55, 73, 91, 38, 60, 78, 85. Find the mean, median, and range.', 'Mean = (45+67+82+55+73+91+38+60+78+85)/10 = 674/10 = 67.4. Sorted: 38,45,55,60,67,73,78,82,85,91. Median = (67+73)/2 = 70. Range = 91-38 = 53.', 3),
            ('very_short', 'What is 2³?', '8', 1),
            ('very_short', 'Solve: x/4 = 9', '36', 1),
            ('short', 'Find the circumference of a circle with radius 7 cm (use π = 22/7).', 'C = 2πr = 2 × 22/7 × 7 = 44 cm', 2),
        ],
        8: [
            ('very_short', 'Factorise: x² - 9', '(x+3)(x-3)', 1),
            ('very_short', 'What is the cube root of 27?', '3', 1),
            ('very_short', 'What is 25% of 360?', '90', 1),
            ('short', 'Find the compound interest on ₹10000 at 5% per annum for 2 years.', 'A = 10000(1+5/100)² = 10000 × 1.1025 = ₹11025. CI = 11025-10000 = ₹1025.', 2),
            ('short', 'Solve: 2x + 5 = 3x - 7', '2x + 5 = 3x - 7 → 5 + 7 = 3x - 2x → x = 12', 2),
            ('short', 'Find the area of a trapezium with parallel sides 8 cm and 12 cm, and height 5 cm.', 'Area = 1/2 × (8+12) × 5 = 1/2 × 20 × 5 = 50 sq cm', 2),
            ('long', 'A cylindrical tank has a radius of 7 m and height of 10 m. Find its volume and total surface area (use π = 22/7).', 'Volume = πr²h = 22/7 × 49 × 10 = 1540 cubic m. TSA = 2πr(h+r) = 2 × 22/7 × 7 × (10+7) = 44 × 17 = 748 sq m.', 3),
            ('very_short', 'Simplify: 3⁴ ÷ 3²', '9', 1),
            ('very_short', 'What is the probability of getting heads when flipping a coin?', '1/2', 1),
            ('short', 'Find the value of x: 5(x-2) = 3(x+4)', '5x-10 = 3x+12 → 2x = 22 → x = 11', 2),
        ],
        9: [
            ('very_short', 'Factorise: x² + 5x + 6', '(x+2)(x+3)', 1),
            ('very_short', 'What is the value of sin 30°?', '1/2', 1),
            ('very_short', 'Find the distance between points (0,0) and (3,4).', '5', 1),
            ('short', 'Solve the quadratic: x² - 7x + 12 = 0', 'x² - 7x + 12 = 0 → (x-3)(x-4) = 0 → x = 3 or x = 4', 2),
            ('short', 'Find the surface area of a sphere with radius 7 cm (use π = 22/7).', 'SA = 4πr² = 4 × 22/7 × 49 = 616 sq cm', 2),
            ('short', 'In an AP, if a = 5 and d = 3, find the 10th term.', 'a₁₀ = a + 9d = 5 + 9×3 = 5 + 27 = 32', 2),
            ('long', 'Prove that the sum of angles in a triangle is 180°. Use the concept of parallel lines and transversals.', 'Draw line PQ parallel to BC through vertex A. Angle PAB = angle ABC (alternate interior angles). Angle QAC = angle ACB (alternate interior angles). Angles PAB + BAC + QAC = 180° (straight line). Therefore angle ABC + BAC + ACB = 180°.', 3),
            ('very_short', 'What is cos 60°?', '1/2', 1),
            ('very_short', 'What is the slope of y = 3x + 2?', '3', 1),
            ('short', 'Find the median of: 3, 7, 2, 9, 5, 11, 4', 'Sorted: 2,3,4,5,7,9,11. Median = 5 (middle value)', 2),
        ],
        10: [
            ('very_short', 'What is the discriminant of x² - 4x + 4 = 0?', '0', 1),
            ('very_short', 'Find the value of tan 45°.', '1', 1),
            ('very_short', 'What is the sum of first 10 natural numbers?', '55', 1),
            ('short', 'Solve using quadratic formula: 2x² - 5x + 2 = 0', 'D = 25-16 = 9. x = (5±3)/4. x = 2 or x = 1/2.', 2),
            ('short', 'Find the sum of first 20 terms of AP: 3, 7, 11, 15...', 'a=3, d=4, n=20. S₂₀ = 20/2 × [2(3) + 19(4)] = 10 × [6+76] = 10 × 82 = 820', 2),
            ('short', 'A cone has radius 5 cm and height 12 cm. Find its slant height.', 'l = √(r²+h²) = √(25+144) = √169 = 13 cm', 2),
            ('long', 'From the top of a 45m high lighthouse, the angle of depression of a ship is 30°. Find the distance of the ship from the base of the lighthouse. Explain step by step.', 'Let distance = d. tan 30° = 45/d. 1/√3 = 45/d. d = 45√3 = 45 × 1.732 = 77.94 m ≈ 77.9 m.', 3),
            ('very_short', 'What is the common ratio of GP: 2, 6, 18, 54?', '3', 1),
            ('very_short', 'If P(A) = 0.3, what is P(not A)?', '0.7', 1),
            ('short', 'Find the coordinates of the midpoint of (2,5) and (8,11).', 'Midpoint = ((2+8)/2, (5+11)/2) = (5, 8)', 2),
        ],
    },
    'Science': {
        1: [
            ('very_short', 'What do plants need to grow?', 'Water and sunlight', 1),
            ('very_short', 'Name one body part used for seeing.', 'Eyes', 1),
            ('short', 'Name three animals that live in water.', 'Fish, frog, and turtle live in water.', 2),
            ('short', 'What happens when you push a ball?', 'When you push a ball, it moves in the direction you push it.', 2),
            ('long', 'Name five things you see in the sky during the day and at night. How is the sky different?', 'Day: Sun, clouds, birds, airplane, blue sky. Night: Moon, stars, bats, darkness, planets. During the day the sky is bright because of the sun, and at night it is dark with stars visible.', 3),
            ('very_short', 'What color are most leaves?', 'Green', 1),
            ('very_short', 'Which is hotter: ice or fire?', 'Fire', 1),
            ('short', 'Name two things made of wood.', 'Table and chair are made of wood.', 2),
            ('very_short', 'What do we breathe?', 'Air', 1),
            ('short', 'Why do we need food?', 'We need food to get energy and to grow healthy and strong.', 2),
        ],
        2: [
            ('very_short', 'What is the baby of a cat called?', 'Kitten', 1),
            ('very_short', 'Name the star closest to Earth.', 'Sun', 1),
            ('short', 'What are the three states of water?', 'The three states of water are solid (ice), liquid (water), and gas (steam/water vapor).', 2),
            ('short', 'Why do we need to drink water every day?', 'We need water to stay hydrated, for digestion, and to keep our body working properly.', 2),
            ('long', 'Describe the lifecycle of a butterfly in your own words.', 'A butterfly starts as an egg laid on a leaf. It hatches into a caterpillar (larva) which eats leaves and grows. Then it forms a chrysalis (pupa). Inside it transforms and finally comes out as a beautiful adult butterfly.', 3),
            ('very_short', 'What gives us light during the day?', 'The Sun', 1),
            ('very_short', 'How many legs does a spider have?', '8', 1),
            ('short', 'Name three fruits that are red in color.', 'Apple, strawberry, and cherry are red fruits.', 2),
            ('very_short', 'What is the opposite of hot?', 'Cold', 1),
            ('short', 'What is the difference between living and non-living things?', 'Living things grow, breathe, eat, and reproduce. Non-living things do not.', 2),
        ],
        3: [
            ('very_short', 'What planet do we live on?', 'Earth', 1),
            ('very_short', 'What is H₂O?', 'Water', 1),
            ('short', 'Name the four cardinal directions.', 'North, South, East, and West.', 2),
            ('short', 'Why do birds have wings?', 'Birds have wings to fly, which helps them find food, escape predators, and migrate.', 2),
            ('long', 'Explain the water cycle in your own words.', 'Water from rivers, lakes, and oceans evaporates due to heat from the sun. The water vapor rises and cools to form clouds (condensation). When clouds get heavy, water falls back as rain or snow (precipitation). This water flows back into rivers and oceans, and the cycle repeats.', 3),
            ('very_short', 'What is the largest organ of the human body?', 'Skin', 1),
            ('very_short', 'Name the gas we breathe out.', 'Carbon dioxide', 1),
            ('short', 'What is the difference between herbivores and carnivores?', 'Herbivores eat only plants. Carnivores eat only other animals.', 2),
            ('very_short', 'How many bones does an adult human have?', '206', 1),
            ('short', 'Name three sources of light.', 'Sun, bulb/lamp, and fire are sources of light.', 2),
        ],
        4: [
            ('very_short', 'What is the boiling point of water in Celsius?', '100', 1),
            ('very_short', 'What type of rock is formed from cooled lava?', 'Igneous', 1),
            ('short', 'Name the four types of teeth in humans.', 'Incisors, canines, premolars, and molars.', 2),
            ('short', 'What is photosynthesis?', 'Photosynthesis is the process by which plants make food using sunlight, water, and carbon dioxide, producing oxygen.', 2),
            ('long', 'Describe the digestive system and name its main organs.', 'Food enters through the mouth where it is chewed. It passes through the esophagus to the stomach. The stomach breaks it down with acids. Then it moves to the small intestine where nutrients are absorbed. The large intestine absorbs water and the waste is expelled.', 3),
            ('very_short', 'What is the chemical symbol for iron?', 'Fe', 1),
            ('very_short', 'Name the closest planet to the Sun.', 'Mercury', 1),
            ('short', 'What causes day and night?', 'Day and night are caused by the rotation of the Earth on its axis.', 2),
            ('very_short', 'What force pulls objects toward Earth?', 'Gravity', 1),
            ('short', 'Name three renewable sources of energy.', 'Solar energy, wind energy, and hydroelectric energy.', 2),
        ],
        5: [
            ('very_short', 'What is the speed of light approximately?', '3 × 10⁸ m/s', 1),
            ('very_short', 'What is the chemical formula of table salt?', 'NaCl', 1),
            ('short', 'Explain the difference between a conductor and an insulator.', 'A conductor allows electricity to pass through it (like copper). An insulator does not allow electricity to pass through (like rubber).', 2),
            ('short', 'What are the three types of muscles in the human body?', 'Skeletal muscles, smooth muscles, and cardiac muscles.', 2),
            ('long', 'Describe how the human respiratory system works.', 'We breathe in air through the nose/mouth. Air travels down the trachea, into bronchi, and then into bronchioles in the lungs. At the alveoli, oxygen passes into the blood and carbon dioxide passes out. We then breathe out the carbon dioxide.', 3),
            ('very_short', 'How many planets are in our solar system?', '8', 1),
            ('very_short', 'What is the freezing point of water?', '0°C', 1),
            ('short', 'What is an ecosystem?', 'An ecosystem is a community of living organisms interacting with each other and their physical environment.', 2),
            ('very_short', 'What causes rust on iron?', 'Oxygen and moisture', 1),
            ('short', 'Name the layers of the Earth.', 'Crust, mantle, outer core, and inner core.', 2),
        ],
        6: [
            ('very_short', 'What is the SI unit of force?', 'Newton', 1),
            ('very_short', 'Name the process by which cells divide.', 'Mitosis', 1),
            ('short', 'What is the difference between a physical change and a chemical change?', 'Physical change: no new substance is formed (e.g., melting ice). Chemical change: a new substance is formed (e.g., rusting iron).', 2),
            ('short', 'Explain the function of white blood cells.', 'White blood cells fight infections and protect the body from diseases by destroying bacteria and viruses.', 2),
            ('long', 'Explain the structure of an atom, including subatomic particles.', 'An atom has a central nucleus containing protons (positive charge) and neutrons (no charge). Electrons (negative charge) orbit the nucleus in shells. The atomic number equals the number of protons.', 3),
            ('very_short', 'What is the pH of pure water?', '7', 1),
            ('very_short', 'What organ pumps blood in the human body?', 'Heart', 1),
            ('short', 'What is density? Write its formula.', 'Density is mass per unit volume. Formula: Density = Mass/Volume.', 2),
            ('very_short', 'What type of lens is used in a magnifying glass?', 'Convex', 1),
            ('short', 'Name three properties of acids.', 'Acids taste sour, turn blue litmus red, and react with metals to produce hydrogen gas.', 2),
        ],
        7: [
            ('very_short', 'What is Newton\'s first law also called?', 'Law of Inertia', 1),
            ('very_short', 'What is the chemical formula of glucose?', 'C₆H₁₂O₆', 1),
            ('short', 'What is the difference between speed and velocity?', 'Speed is the distance covered per unit time (scalar). Velocity is speed with direction (vector).', 2),
            ('short', 'Explain the function of kidneys in the human body.', 'Kidneys filter blood to remove waste products and excess water, producing urine. They also regulate blood pressure and electrolyte balance.', 2),
            ('long', 'Describe the process of respiration in plants. How is it different from photosynthesis?', 'Plants respire by taking in oxygen and releasing carbon dioxide, breaking down glucose for energy. This happens all the time. Photosynthesis is the opposite: plants take in CO₂ and release O₂, using sunlight to make glucose. Photosynthesis only happens in light.', 3),
            ('very_short', 'What is the unit of electric current?', 'Ampere', 1),
            ('very_short', 'What planet is known as the Red Planet?', 'Mars', 1),
            ('short', 'What is Ohm\'s Law?', 'V = IR, where V is voltage, I is current, and R is resistance.', 2),
            ('very_short', 'What is the hardest natural substance?', 'Diamond', 1),
            ('short', 'What are the products of photosynthesis?', 'Glucose and oxygen.', 2),
        ],
        8: [
            ('very_short', 'What is the atomic number of Carbon?', '6', 1),
            ('very_short', 'What is the SI unit of pressure?', 'Pascal', 1),
            ('short', 'Explain the difference between metals and non-metals with two examples each.', 'Metals: good conductors, malleable (e.g., iron, copper). Non-metals: poor conductors, brittle (e.g., sulfur, phosphorus).', 2),
            ('short', 'What is the law of conservation of energy?', 'Energy cannot be created or destroyed, only transformed from one form to another. The total energy in a closed system remains constant.', 2),
            ('long', 'Explain the human circulatory system, including the role of the heart, arteries, veins, and capillaries.', 'The heart pumps blood through two circuits. Arteries carry oxygenated blood away from the heart. Veins carry deoxygenated blood back to the heart. Capillaries are tiny vessels where gas exchange occurs. The right side pumps blood to the lungs (pulmonary), and the left side pumps to the body (systemic).', 3),
            ('very_short', 'What gas do plants absorb during photosynthesis?', 'Carbon dioxide', 1),
            ('very_short', 'Name the force that opposes motion.', 'Friction', 1),
            ('short', 'What is an alloy? Give two examples.', 'An alloy is a mixture of two or more metals. Examples: Brass (copper + zinc), Steel (iron + carbon).', 2),
            ('very_short', 'What is the valency of Oxygen?', '2', 1),
            ('short', 'Explain reflection of light.', 'When light hits a smooth surface, it bounces back. The angle of incidence equals the angle of reflection.', 2),
        ],
        9: [
            ('very_short', 'What is the acceleration due to gravity on Earth?', '9.8 m/s²', 1),
            ('very_short', 'What is the molecular formula of water?', 'H₂O', 1),
            ('short', 'State Newton\'s second law of motion and write its formula.', 'The force acting on an object is equal to its mass times its acceleration. F = ma.', 2),
            ('short', 'What is the difference between an element and a compound?', 'An element is made of one type of atom (e.g., oxygen). A compound is made of two or more elements chemically bonded (e.g., water H₂O).', 2),
            ('long', 'Describe the structure of a cell. Compare plant and animal cells.', 'Both have cell membrane, cytoplasm, nucleus, mitochondria, and ribosomes. Plant cells additionally have a cell wall, chloroplasts, and a large central vacuole. Animal cells have smaller vacuoles and may have lysosomes.', 3),
            ('very_short', 'What is the SI unit of work?', 'Joule', 1),
            ('very_short', 'What is the chemical formula of methane?', 'CH₄', 1),
            ('short', 'What is the difference between mass and weight?', 'Mass is the amount of matter (measured in kg, constant). Weight is the force of gravity on mass (measured in N, varies with location).', 2),
            ('very_short', 'Name the smallest unit of life.', 'Cell', 1),
            ('short', 'What are isotopes? Give an example.', 'Isotopes are atoms of the same element with different numbers of neutrons. Example: Carbon-12 and Carbon-14.', 2),
        ],
        10: [
            ('very_short', 'What is the atomic number of Sodium?', '11', 1),
            ('very_short', 'What is the SI unit of electric resistance?', 'Ohm', 1),
            ('short', 'State Ohm\'s law and draw the V-I graph for a resistor.', 'V = IR. The V-I graph for a resistor is a straight line through the origin, showing voltage is directly proportional to current.', 2),
            ('short', 'What is the difference between ionic and covalent bonds?', 'Ionic bonds form by transfer of electrons (e.g., NaCl). Covalent bonds form by sharing electrons (e.g., H₂O).', 2),
            ('long', 'Explain the process of natural selection and its role in evolution.', 'In a population, individuals show variation. Those with traits better suited to the environment are more likely to survive and reproduce (survival of the fittest). These advantageous traits are passed to offspring. Over many generations, the population evolves as these traits become more common.', 3),
            ('very_short', 'What is the power of a lens with focal length 50 cm?', '2 diopters', 1),
            ('very_short', 'Name the hormone that controls blood sugar.', 'Insulin', 1),
            ('short', 'Balance the equation: Fe + O₂ → Fe₂O₃', '4Fe + 3O₂ → 2Fe₂O₃', 2),
            ('very_short', 'What is the functional group of alcohols?', '-OH', 1),
            ('short', 'What is electromagnetic induction?', 'It is the production of an electric current by changing the magnetic field around a conductor, discovered by Faraday.', 2),
        ],
    },
    'English': {
        1: [
            ('very_short', 'What is the opposite of "big"?', 'Small', 1),
            ('very_short', 'Fill in the blank: The cat is ___ the mat. (on/in)', 'on', 1),
            ('short', 'Make a sentence using the word "happy".', 'I feel happy when I play with my friends.', 2),
            ('short', 'Name three animals that start with the letter "D".', 'Dog, duck, and deer.', 2),
            ('long', 'Write 3-4 sentences about your favorite animal.', 'My favorite animal is the dog. Dogs are friendly and loyal. They love to play and run. I like to take my dog for walks in the park.', 3),
            ('very_short', 'What is the plural of "cat"?', 'Cats', 1),
            ('very_short', 'Which letter comes after M?', 'N', 1),
            ('short', 'What is a noun? Give an example.', 'A noun is a naming word. Examples: dog, school, book.', 2),
            ('very_short', 'Fill in: She ___ playing. (is/are)', 'is', 1),
            ('short', 'Rearrange to make a sentence: "is / a / This / book"', 'This is a book.', 2),
        ],
        2: [
            ('very_short', 'What is the past tense of "go"?', 'Went', 1),
            ('very_short', 'What is the opposite of "fast"?', 'Slow', 1),
            ('short', 'Write a sentence using the word "because".', 'I brought an umbrella because it was raining.', 2),
            ('short', 'What is an adjective? Give two examples.', 'An adjective describes a noun. Examples: tall, beautiful.', 2),
            ('long', 'Write a short paragraph (4-5 sentences) about your school.', 'My school is big and beautiful. It has many classrooms and a playground. My favorite subject is English. I have many friends at school. We play together during recess.', 3),
            ('very_short', 'What is the plural of "child"?', 'Children', 1),
            ('very_short', 'What punctuation mark ends a question?', 'Question mark (?)', 1),
            ('short', 'What is a verb? Give two examples.', 'A verb is an action word. Examples: run, eat.', 2),
            ('very_short', 'Fill in: They ___ going to school. (is/are)', 'are', 1),
            ('short', 'Write rhyming words for "cat" (at least 3).', 'Bat, hat, mat, rat, sat.', 2),
        ],
        3: [
            ('very_short', 'What is a synonym for "happy"?', 'Glad/joyful', 1),
            ('very_short', 'What is the comparative form of "good"?', 'Better', 1),
            ('short', 'What is a pronoun? Name three pronouns.', 'A pronoun replaces a noun. Examples: he, she, they.', 2),
            ('short', 'Change to past tense: "She eats an apple every day."', 'She ate an apple every day.', 2),
            ('long', 'Write a short story (5-6 sentences) about a rainy day.', 'One morning I woke up to the sound of rain. The sky was grey and cloudy. I wore my raincoat and boots. At school, we could not play outside. Instead, we read stories in class. When the rain stopped, a beautiful rainbow appeared.', 3),
            ('very_short', 'What is the opposite of "empty"?', 'Full', 1),
            ('very_short', 'What type of sentence ends with "!"?', 'Exclamatory', 1),
            ('short', 'What is the difference between "there", "their", and "they\'re"?', 'There = a place. Their = belonging to them. They\'re = they are.', 2),
            ('very_short', 'Name the article in: "an apple".', 'an', 1),
            ('short', 'Punctuate: "do you like ice cream"', 'Do you like ice cream?', 2),
        ],
        4: [
            ('very_short', 'What is a synonym for "brave"?', 'Courageous', 1),
            ('very_short', 'What is the superlative of "tall"?', 'Tallest', 1),
            ('short', 'What is a conjunction? Give three examples.', 'A conjunction joins words or sentences. Examples: and, but, or.', 2),
            ('short', 'Convert to indirect speech: She said, "I am going home."', 'She said that she was going home.', 2),
            ('long', 'Write a letter to your friend inviting them to your birthday party.', 'Dear Priya, I am writing to invite you to my birthday party. It will be held at my house on Saturday at 4 PM. There will be games, cake, and snacks. I would love for you to come. Please let me know if you can make it. Your friend, [Name].', 3),
            ('very_short', 'What is the plural of "mouse"?', 'Mice', 1),
            ('very_short', 'What part of speech is "quickly"?', 'Adverb', 1),
            ('short', 'What is the difference between a simile and a metaphor?', 'A simile compares using "like" or "as" (e.g., fast as a cheetah). A metaphor says something IS something else (e.g., time is money).', 2),
            ('very_short', 'What is the antonym of "ancient"?', 'Modern', 1),
            ('short', 'Identify the subject and predicate: "The tall boy ran quickly."', 'Subject: The tall boy. Predicate: ran quickly.', 2),
        ],
        5: [
            ('very_short', 'What is a homophone for "write"?', 'Right', 1),
            ('very_short', 'Name the tense: "She will go tomorrow."', 'Future tense', 1),
            ('short', 'What is an idiom? Give an example with its meaning.', 'An idiom is a phrase with a figurative meaning. Example: "It\'s raining cats and dogs" means it\'s raining heavily.', 2),
            ('short', 'Convert to passive voice: "The dog chased the cat."', 'The cat was chased by the dog.', 2),
            ('long', 'Write a paragraph about the importance of reading books.', 'Reading books is very important for personal growth. Books increase our knowledge and vocabulary. They improve our imagination and creativity. Reading also helps us concentrate better. Whether fiction or non-fiction, every book teaches us something new. Students who read regularly perform better in studies.', 3),
            ('very_short', 'What figure of speech is "The wind howled"?', 'Personification', 1),
            ('very_short', 'What is the past participle of "write"?', 'Written', 1),
            ('short', 'Use "affect" and "effect" correctly in sentences.', 'The rain will affect our plans. The effect of the rain was flooding.', 2),
            ('very_short', 'What is a prefix? Give an example.', 'A prefix is added before a word. Example: un- in unhappy.', 1),
            ('short', 'What is the difference between "than" and "then"?', 'Than is used for comparison (taller than). Then refers to time (and then we left).', 2),
        ],
        6: [
            ('very_short', 'What is an oxymoron?', 'A figure of speech combining contradictory words', 1),
            ('very_short', 'What is the past tense of "swim"?', 'Swam', 1),
            ('short', 'What is the difference between a phrase and a clause?', 'A phrase is a group of words without a subject-verb pair. A clause has a subject and a verb.', 2),
            ('short', 'Convert to reported speech: He said, "I have finished my homework."', 'He said that he had finished his homework.', 2),
            ('long', 'Write a debate argument for or against: "Social media is beneficial for students."', 'Social media can be beneficial for students as it provides access to educational resources and connects them with peers globally. Students can join study groups and follow educational pages. However, it must be used responsibly. Time limits should be set to avoid distraction. When used wisely, social media is a powerful learning tool.', 3),
            ('very_short', 'Give an example of alliteration.', 'Peter Piper picked a peck of pickled peppers', 1),
            ('very_short', 'What is the plural of "criterion"?', 'Criteria', 1),
            ('short', 'What is a thesis statement?', 'A thesis statement is the main argument or point of an essay, usually stated in the introduction.', 2),
            ('very_short', 'What literary device is "She sells seashells"?', 'Alliteration', 1),
            ('short', 'Explain the difference between "who" and "whom".', 'Who is used as a subject (Who is calling?). Whom is used as an object (To whom did you give it?).', 2),
        ],
        7: [
            ('very_short', 'What is an antonym for "benevolent"?', 'Malevolent', 1),
            ('very_short', 'Identify the figure of speech: "Life is a journey."', 'Metaphor', 1),
            ('short', 'What is the difference between "its" and "it\'s"?', '"Its" is possessive (The dog wagged its tail). "It\'s" is a contraction of "it is" (It\'s raining today).', 2),
            ('short', 'Change to passive voice: "The teacher praised the students."', 'The students were praised by the teacher.', 2),
            ('long', 'Write a summary of any story or fable you know in 5-6 sentences.', 'The Tortoise and the Hare is a famous fable. A hare mocked a slow tortoise and challenged him to a race. The hare ran fast but became overconfident and took a nap. The tortoise kept walking steadily without stopping. When the hare woke up, the tortoise had already crossed the finish line. The moral is: slow and steady wins the race.', 3),
            ('very_short', 'What is the noun form of "beautiful"?', 'Beauty', 1),
            ('very_short', 'Name a conjunction that shows contrast.', 'But/however', 1),
            ('short', 'What is dramatic irony?', 'When the audience knows something that the characters in the story do not know.', 2),
            ('very_short', 'What is the adjective form of "danger"?', 'Dangerous', 1),
            ('short', 'Identify the type of sentence: "What a beautiful day it is!"', 'Exclamatory sentence.', 2),
        ],
        8: [
            ('very_short', 'What does "ephemeral" mean?', 'Lasting for a very short time', 1),
            ('very_short', 'What is a soliloquy?', 'A speech in a play where a character speaks their thoughts aloud', 1),
            ('short', 'What is the difference between denotation and connotation?', 'Denotation is the literal dictionary meaning of a word. Connotation is the emotional or cultural association of a word.', 2),
            ('short', 'Transform into a compound sentence: "It was raining. We stayed inside."', 'It was raining, so we stayed inside.', 2),
            ('long', 'Write a persuasive paragraph on why students should read newspapers.', 'Reading newspapers is essential for students. It keeps them updated on current affairs and world events. It improves vocabulary and reading skills. Newspapers expose students to diverse viewpoints and critical thinking. Editorials teach them to form and express opinions. In competitive exams, general knowledge from newspapers is invaluable.', 3),
            ('very_short', 'What is the plural of "phenomenon"?', 'Phenomena', 1),
            ('very_short', 'Name the literary term for exaggeration.', 'Hyperbole', 1),
            ('short', 'What is a dangling modifier? Give an example.', 'A modifier that doesn\'t clearly refer to the word it modifies. Example: "Running quickly, the finish line was reached." (Who was running?)', 2),
            ('very_short', 'What is the adjective form of "hero"?', 'Heroic', 1),
            ('short', 'What is the difference between "farther" and "further"?', 'Farther refers to physical distance. Further means additional or more (figurative).', 2),
        ],
        9: [
            ('very_short', 'What does "ubiquitous" mean?', 'Present everywhere', 1),
            ('very_short', 'What is blank verse?', 'Unrhymed iambic pentameter', 1),
            ('short', 'What is the difference between a tragedy and a comedy in literature?', 'A tragedy ends in suffering or death of the hero. A comedy ends happily, often with humor and resolution.', 2),
            ('short', 'What is a paradox? Give an example.', 'A statement that seems contradictory but reveals a truth. Example: "The only constant is change."', 2),
            ('long', 'Write a critical analysis of the theme of any poem or story you have studied.', 'In Robert Frost\'s "The Road Not Taken," the theme explores choices and their consequences. The speaker faces two paths in a forest, symbolizing life decisions. He chooses the less traveled path, representing individuality. The poem suggests that our choices define us. The final line "that has made all the difference" shows both pride and uncertainty about our decisions.', 3),
            ('very_short', 'What is an elegy?', 'A poem mourning the death of someone', 1),
            ('very_short', 'What is the verb form of "decision"?', 'Decide', 1),
            ('short', 'What is stream of consciousness writing?', 'A narrative technique that presents a character\'s continuous flow of thoughts and feelings as they occur.', 2),
            ('very_short', 'Name one work by Shakespeare.', 'Hamlet/Romeo and Juliet/Macbeth', 1),
            ('short', 'What is the difference between a protagonist and an antagonist?', 'The protagonist is the main character. The antagonist opposes the protagonist.', 2),
        ],
        10: [
            ('very_short', 'What does "pragmatic" mean?', 'Practical, dealing with things sensibly', 1),
            ('very_short', 'What is a sonnet?', 'A 14-line poem with a specific rhyme scheme', 1),
            ('short', 'What is the difference between satire and parody?', 'Satire uses humor to criticize society or individuals. Parody imitates a specific work for comic effect.', 2),
            ('short', 'Explain the concept of "unreliable narrator".', 'An unreliable narrator is a character whose telling of the story cannot be fully trusted due to bias, limited knowledge, or deception.', 2),
            ('long', 'Write an essay outline on: "The impact of technology on modern education."', 'Introduction: Technology has revolutionized education. Thesis: While technology enhances learning, it requires balanced implementation. Body 1: Benefits - online resources, interactive learning, global access. Body 2: Challenges - digital divide, distraction, reduced face-to-face interaction. Body 3: Solutions - structured screen time, teacher training, blended learning. Conclusion: Technology is a powerful tool when used wisely in education.', 3),
            ('very_short', 'What is an anaphora?', 'Repetition of a word at the beginning of successive clauses', 1),
            ('very_short', 'What is the meaning of "cogent"?', 'Clear, logical, and convincing', 1),
            ('short', 'What is the difference between "lay" and "lie"?', 'Lay means to put down (transitive: lay the book down). Lie means to recline (intransitive: lie on the bed).', 2),
            ('very_short', 'What literary period does Shakespeare belong to?', 'Renaissance/Elizabethan', 1),
            ('short', 'What is the purpose of a couplet at the end of a Shakespearean sonnet?', 'The couplet provides a conclusion, twist, or summary of the poem\'s theme in the final two rhyming lines.', 2),
        ],
    },
}

def seed_questions():
    with app.app_context():
        if Question.query.count() > 0:
            print('Questions already exist. Skipping seed.')
            return

        subjects = {s.name: s.id for s in Subject.query.all()}
        count = 0

        for subject_name, grades in QUESTIONS.items():
            subject_id = subjects.get(subject_name)
            if not subject_id:
                print(f'Subject "{subject_name}" not found, skipping.')
                continue
            for grade, questions in grades.items():
                for q_type, q_text, q_answer, marks in questions:
                    q = Question(
                        grade=grade,
                        subject_id=subject_id,
                        question_type=q_type,
                        question_text=q_text,
                        correct_answer=q_answer,
                        marks=marks
                    )
                    db.session.add(q)
                    count += 1

        db.session.commit()
        print(f'Seeded {count} questions across {len(QUESTIONS)} subjects and grades 1-10.')


if __name__ == '__main__':
    seed_questions()
